import {
  OpenAILogo,
  AgnoIcon,
  UserIcon,
  AgentIcon,
  MistralLogo,
  GeminiLogo,
  AwsLogo,
  AzureLogo,
  AnthropicLogo,
  GroqLogo,
  FireworksLogo,
  DeepseekLogo,
  CohereLogo,
  OllamaLogo,
  XaiLogo,
  SheetIcon,
  NextjsTag,
  ShadcnTag
} from './custom-icons'
import { IconTypeMap } from './types'
import {
  RefreshCw,
  Edit,
  Save,
  X,
  ArrowDown,
  ArrowLeft,
  SendIcon,
  Download,
  HammerIcon,
  Check,
  ChevronDown,
  ChevronUp,
  Trash,
  LogOut,
  Paperclip,
  Brain,
  Settings,
  Image,
  Cpu,
  Workflow,
  Link,
  MessageCircle,
  Key,
  Calendar,
  QrCode,
  Bot,
  MoreHorizontal,
  Play,
  Square,
  Trash2,
  Loader2,
  Copy,
  AlertCircle,
  Database,
  FileText,
  Plus,
  Users,
  BookOpen
} from 'lucide-react'

import { PlusIcon } from '@radix-ui/react-icons'
import {
  BsWhatsapp,
  BsTelegram,
  BsDiscord,
  BsSlack,
  BsFacebook,
  BsInstagram,
  BsInfoCircle,
  BsClock,
  BsServer,
  BsCheckCircle,
  BsDot
} from 'react-icons/bs'

export const ICONS: IconTypeMap = {
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  agno: AgnoIcon,
  'agno-tag': AgnoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  x: X,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'plus-icon': PlusIcon,
  trash: Trash,
  'log-out': LogOut,
  paperclip: Paperclip,
  brain: Brain,
  settings: Settings,
  image: Image,
  cpu: Cpu,
  workflow: Workflow,
  link: Link,
  'message-circle': MessageCircle,
  key: Key,
  calendar: Calendar,
  'qr-code': QrCode,
  bot: Bot,
  'more-horizontal': MoreHorizontal,
  play: Play,
  square: Square,
  'refresh-cw': RefreshCw,
  'trash-2': Trash2,
  'loader-2': Loader2,
  copy: Copy,
  'alert-circle': AlertCircle,
  database: Database,
  'file-text': FileText,
  plus: Plus,
  users: Users,
  'book-open': BookOpen,
  whatsapp: BsWhatsapp,
  telegram: BsTelegram,
  discord: BsDiscord,
  slack: BsSlack,
  messenger: BsFacebook,
  info: BsInfoCircle,
  clock: BsClock,
  server: BsServer,
  'check-circle': BsCheckCircle,
  instagram: BsInstagram,
  facebook: BsFacebook,
  dot: BsDot
}
